# Generated by Django 3.1.1 on 2020-12-29 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webap', '0004_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='files',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.CreateModel(
            name='ContentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to=settings.AUTH_USER_MODEL)),
                ('phone_numbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Webap.content')),
            ],
            options={
                'verbose_name_plural': 'content images',
                'db_table': 'tbl_content_images',
                'managed': True,
            },
        ),
    ]
